# Sample Config - expected in ~/.fh-cup.toml
IP = "192.168.44.10" # Optional

# Required - Used to determine where to put cluster persistence files/directories. Important - use a full path.
FhCupDir = "/path-to-gospace/src/github.com/feedhenry/fh-cup"

CoreOpenShiftTemplates = "/path-to/fh-core-openshift-templates" # Required - Important, use a full path here
MBaaSOpenShiftTemplates = "/path-to/fh-openshift-templates" # Required - Important, use a full path here
DockerUsername = "dockerhub-username" # Required
DockerPassword = "dockerhub-password" # Required
DockerEmail = "dockerhub-email" # Required
ClusterDomain = "cup.feedhenry.io" # Optional
FhcTarget = "rhmap.cup.feedhenry.io" # Optional
FhcUsername = "rhmap-admin@example.com" # Optional
FhcPassword = "Password1" # Optional

RhmapAnsibleDir = "/path-to/rhmap-ansible" # Required - Important, use a full path here
RhmapAnsibleImage = "docker.io/philipgough/rhmap-ansible" # Optional - Docker image for rhmap-ansible
